DROP TABLE ODONTOLOGOS IF EXISTS;

CREATE TABLE ODONTOLOGOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MATRICULA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL
);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 95664, 'JUAN', 'ARTEAGA'), (DEFAULT, 88524, 'MARIA', 'GONZALEZ');
